Basic Array Creation

In [ ]:
import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("Array from list:",array_from_list)

Array from list: [1 2 3 4 5]


In [ ]:
array_with_range=np.arange(10)
print("Array with range:",array_with_range)


Array with range: [0 1 2 3 4 5 6 7 8 9]


creating an array with a range of values

creating an array of zeros

In [ ]:
zeros_array=np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


creating an array of ones

In [ ]:
ones_array=np.ones((2,5))
print("Array of ones:\n",ones_array)

Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array Operations

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


element-wise addition

In [ ]:
add_result=np.add(a,b)
print("Addition:",add_result)

Addition: [5 7 9]


element-wise subtraction

In [ ]:
sub_result=np.subtract(a,b)
print("Subtractio:",sub_result)

Subtractio: [-3 -3 -3]


element

In [ ]:
mul_result=np.multiply(a,b)
print("Multiplication:",mul_result)

Multiplication: [ 4 10 18]


element-wise division

In [ ]:
div_result=np.divide(a,b)
print("Division:",div_result)

Division: [0.25 0.4  0.5 ]


creating a 1D array

In [ ]:
array=np.arange(12)
print("Original array:",array)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


reshaping to 2D array(3X4)

In [ ]:
reshaped_array=array.reshape((3,4))
print("Reshaped to 3x4:\n",reshaped_array)

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


reshaping to 3D array(2x3x2)

In [ ]:
reshaped_array_3d=array.reshape((2,3,2))
print("Reshaped to 2x3x2:\n",reshaped_array_3d)

Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


creating a 2D array

In [ ]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n",array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Accessing element at(1,2)

In [ ]:
element=array_2d[1,2]
print("Element at (1,2):",element)

Element at (1,2): 6


Slicing a subarray(rows 1 to 2,columns 0 to 1)

In [ ]:
subarray=array_2d[1:3,0:2]
print("Sliced subarray:\n",subarray)

Sliced subarray:
 [[4 5]
 [7 8]]


Accessing a column(all rows,column1)

In [ ]:
column=array_2d[:,1]
print("Column1:",column)

Column1: [2 5 8]


statistical operations
creating an array

In [ ]:
array=np.array([1,2,3,4,5,6,7,8,9,10])


Calculating mean

In [ ]:
mean=np.mean(array)
print("Mean:",mean)

Mean: 5.5


Calculating median

In [ ]:
median=np.median(array)
print("Median:",median)

Median: 5.5


Calculating standard deviation

In [ ]:
std_dev=np.std(array)
print("Standard Deviation:",std_dev)

Standard Deviation: 2.8722813232690143


Finding minimum and maximum values

In [ ]:
min_val=np.min(array)
max_val=np.max(array)
print("Minimum value:",min_val)
print("Maximum value:",max_val)

Minimum value: 1
Maximum value: 10
